### ISSUE TITLE
Is it possible to click on elements and extract data by selectors with this plugin?

### ISSUE THREAD

**Issue by PatrickHuetter** [momer/nutch-selenium-grid-plugin#5]
Regarding to my question on stackoverflow ( http://stackoverflow.com/questions/30887701/should-i-use-akka-io-apache-spark-mesos-or-storm-for-a-webcrawling-engine ) i found this and the non-grid plugin. The questions refer to both plugins.

1) Is it possible to click on elements (for example buttons or javascript links) before saving the crawled data? 

2) Is it possible to only save data wich matches a given selector (xpath, css or regex)?

3) Is it possible to use a specific proxy with each crawl-job wich gets executed?

If 1, 2 and 3 aren't possible: Is it possible to extend the plugin with this features easily?

Best regards

**Comment by momer** [comment]
Hey Patrick,

This plugin isn't the one available in Nutch 1.1x trunk (that's the plain Selenium plugin at [nutch-selenium related issues in JIRA](https://issues.apache.org/jira/browse/NUTCH-2021?jql=project%20%3D%20NUTCH%20AND%20text%20~%20%22selenium%22)). So this discussion does fit best here:

1) Sure, but this is custom functionality that I don't see being added in for the general case. If you want, feel free to extend the plugin for your needs.

2) Of course, check out the links below for examples on how to add custom fields

  - http://sujitpal.blogspot.com/2009/07/nutch-custom-plugin-to-parse-and-add.html
  - http://wiki.apache.org/nutch/WritingPluginExample
  - http://wiki.apache.org/nutch/WritingPluginExample-1.2
  - http://wiki.apache.org/nutch/AboutPlugins

3) Yes, you'd need to configure this plugin, or your selenium nodes/hub, to [use a proxy](http://grid.selenium.googlecode.com/git-history/5b3078f83c748db7f9061a39b908daf877c7c55b/src/main/webapp/faq.html#can_i_configure_the_remote_control_to_use_a_custom_httphttps_proxy)

1, 2, and 3 aren't built into this plugin, but following the links above, you should be able to add the functionality yourself!
